name: Deploy

on:
  push:
    branches:
      - master
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          ssh -o StrictHostKeyChecking=no ubuntu@jecnaapi.com 'bash ~/deploy_master.sh'
        elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
          ssh -o StrictHostKeyChecking=no ubuntu@jecnaapi.com 'bash ~/deploy_test.sh'
        fi